apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-ingress
  annotations:
      nginx.org/mergeable-ingress-type: minion
      nginx.org/rewrites: serviceName=n8n-service rewrite=/
spec:
  ingressClassName: nginx
  rules:
  - host: k8sbys3bstn.com
    http:
      paths:
      - path:
        pathType: Prefix
        backend:
          service:
            name: n8n-service
            port:
              number: 5678
