apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-configmap
  namespace: n8n
data:
  GENERIC_TIMEZONE: "Europe/Lisbon"
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_USER: "n8n"
  N8N_SECURE_COOKIE: "false"
  N8N_HOST: "k8sbys3bstn.com"
  N8N_PATH: "/n8n"
  WEBHOOK_URL: "http://k8sbys3bstn.com/n8n"
  WEBHOOK_TUNNEL_URL: "http://k8sbys3bstn.com/n8n"
