apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-ingress
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: k8sbys3bstn.com
    http:
      paths:
      - path: /n8n
        pathType: Prefix
        backend:
          service:
            name: n8n-service
            port:
              number: 5678
