apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace: n8n
spec:
  selector:
    app: n8n
  ports:
  - protocol: TCP
    name: http
    port: 5678
    targetPort: 5678
    nodePort: 30036
  type: NodePort
  
