name: Publish Helm Chart
on:
  workflow_dispatch:
    inputs:
      increment_type:
        description: 'Type d''incrémentation de version'
        required: false
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Modifié pour permettre l'écriture du commit
      packages: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Nécessaire pour les opérations Git
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml semver gitpython yq

      - name: Increment Helm chart version
        id: increment_version
        run: |
          import yaml

          # Load the Chart.yaml file
          with open('Chart.yaml', 'r') as file:
              chart = yaml.safe_load(file)

          # Increment the chart version
          current_version = chart['version']
          major, minor, patch = map(int, current_version.split('.'))
          patch += 1
          new_version = f"{major}.{minor}.{patch}"
          chart['version'] = new_version

          # Save the updated Chart.yaml
          with open('Chart.yaml', 'w') as file:
              yaml.safe_dump(chart, file)

          # Output the new version
          print(f"::set-output name=new_version::{new_version}")

      - name: Commit updated Chart.yaml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Chart.yaml
          git commit -m "Increment Helm chart version to ${{ steps.increment_version.outputs.new_version }}"
          git push
          
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Package and Push Helm Chart
        run: |
          # Set variables
          CHART_DIR="."  # Chart is at root level
          CHART_NAME=$(yq e '.name' ./Chart.yaml)
          CHART_VERSION=$(yq e '.version' ./Chart.yaml)
          
          echo "Chart name: $CHART_NAME"
          echo "Chart version: $CHART_VERSION"
          
          # Package the chart locally
          helm package $CHART_DIR
          
          # Use lowercase repository owner (GitHub Container Registry requirement)
          REPO_OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          
          # Push the chart to GitHub Packages with proper formatting
          echo "Pushing to: oci://ghcr.io/${REPO_OWNER_LC}/charts"
          helm push "${CHART_NAME}-${CHART_VERSION}.tgz" "oci://ghcr.io/${REPO_OWNER_LC}/charts"
